// Generated by scripts/generate.mjs — do not edit by hand.
export { IconBase, type IconProps } from "./IconBase.js";

export { Add01 } from "./icons/Add01.js";
export { AlertCircle } from "./icons/AlertCircle.js";
export { ArrowDown01Round } from "./icons/ArrowDown01Round.js";
export { ArrowDown02 } from "./icons/ArrowDown02.js";
export { ArrowLeft01Round } from "./icons/ArrowLeft01Round.js";
export { ArrowRight01Round } from "./icons/ArrowRight01Round.js";
export { ArrowUp01Round } from "./icons/ArrowUp01Round.js";
export { ArrowUp02 } from "./icons/ArrowUp02.js";
export { ArrowUpRight01 } from "./icons/ArrowUpRight01.js";
export { At } from "./icons/At.js";
export { Calendar01 } from "./icons/Calendar01.js";
export { Cancel01 } from "./icons/Cancel01.js";
export { CheckmarkCircle02 } from "./icons/CheckmarkCircle02.js";
export { Clock01 } from "./icons/Clock01.js";
export { ColorPicker } from "./icons/ColorPicker.js";
export { Copy01 } from "./icons/Copy01.js";
export { CreditCard } from "./icons/CreditCard.js";
export { HelpCircle } from "./icons/HelpCircle.js";
export { InformationCircle } from "./icons/InformationCircle.js";
export { Mail01 } from "./icons/Mail01.js";
export { Remove01 } from "./icons/Remove01.js";
export { Search01 } from "./icons/Search01.js";
export { Star } from "./icons/Star.js";
export { Tick02 } from "./icons/Tick02.js";
export { User } from "./icons/User.js";
export { View } from "./icons/View.js";
export { ViewOff } from "./icons/ViewOff.js";

/** Every icon name in this package, as they are named in Figma. */
export const iconNames = [
  "add-01",
  "alert-circle",
  "arrow-down-01-round",
  "arrow-down-02",
  "arrow-left-01-round",
  "arrow-right-01-round",
  "arrow-up-01-round",
  "arrow-up-02",
  "arrow-up-right-01",
  "at",
  "calendar-01",
  "cancel-01",
  "checkmark-circle-02",
  "clock-01",
  "color-picker",
  "copy-01",
  "credit-card",
  "help-circle",
  "information-circle",
  "mail-01",
  "remove-01",
  "search-01",
  "star",
  "tick-02",
  "user",
  "view",
  "view-off",
] as const;
export type IconName = (typeof iconNames)[number];
